// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/lib')['ElAlert'];
    ElAside: typeof import('element-plus/lib')['ElAside'];
    ElButton: typeof import('element-plus/lib')['ElButton'];
    ElContainer: typeof import('element-plus/lib')['ElContainer'];
    ElDivider: typeof import('element-plus/lib')['ElDivider'];
    ElHeader: typeof import('element-plus/lib')['ElHeader'];
    ElIcon: typeof import('element-plus/lib')['ElIcon'];
    ElMain: typeof import('element-plus/lib')['ElMain'];
    ElMenu: typeof import('element-plus/lib')['ElMenu'];
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem'];
    ElTabPane: typeof import('element-plus/lib')['ElTabPane'];
    ElTabs: typeof import('element-plus/lib')['ElTabs'];
    ElTag: typeof import('element-plus/lib')['ElTag'];
    HeaderCom: typeof import('./src/components/HeaderCom.vue')['default'];
    IEpApple: typeof import('~icons/ep/apple')['default'];
    IEpMilkTea: typeof import('~icons/ep/milk-tea')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideMenu: typeof import('./src/components/SideMenu.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/lib')['ElLoadingDirective'];
  }
}
